#!/opt/pwn.college/python

import os
import sys

print("Checking if 'i_have_persistence.txt' exists...\n")

if not os.path.exists("/home/hacker/i_have_persistence.txt"):
    print("The file 'i_have_persistence.txt' does not exist or is in the wrong directory.",
        "The file you created may also be named incorrectly. Please check /home/hacker and try again.\n")
    sys.exit(1)


print("The correct file was found. Printing your flag below...")

with open("/flag") as f:
    print(f.read())
