#!/opt/pwn.college/python

import unittest
import sys
sys.path.append("/challenge")

import modify_me


class TestHelloWorld(unittest.TestCase):
    def test_hello_world(self):
        result = modify_me.hello_world()
        self.assertEqual(result, "Hello World")


# Taken from https://stackoverflow.com/questions/13550039/how-to-use-python-unit-tests-in-self-contained-program
def run_tests(test_case):
    case = unittest.TestLoader().loadTestsFromTestCase(test_case)
    result = unittest.TestResult()
    case(result)
    if result.wasSuccessful():
        print("{0}/{0} tests passed!".format(result.testsRun))
        return True
    
    else:
        print("{0}/{1} tests failed!".format(len(result.failures), result.testsRun))
        for test, err in result.failures + result.errors:
            print("===================")
            print(test)
            print(err)
        
        print("===================")
        return False


if run_tests(TestHelloWorld):
    print("All tests pass! Reading and displaying flag...")
    with open("/flag") as f:
        print(f.read())
else:
    print("Some tests fail. Please review the test cases and errors, then try again.")
